# Generated by Django 5.1 on 2024-09-17 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rkfood_app', '0002_alter_restaurant_close_at_alter_restaurant_opens_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
