# Generated by Django 5.1 on 2024-09-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rkfood_app', '0003_alter_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='_booking_date',
        ),
    ]
