# Generated by Django 5.1 on 2024-09-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rkfood_app', '0004_rename_booking_date_booking__booking_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='_booking_date',
            new_name='booking_date',
        ),
    ]
