# Generated by Django 5.1 on 2024-09-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkfood_app', '0005_rename__booking_date_booking_booking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
