# Generated by Django 5.1 on 2024-09-01 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkfood_app', '0006_payment_order_order_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_ordered', to='rkfood_app.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='menu_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_ordered', to='rkfood_app.menuitems'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
